version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:  npm install

      # Configure the test command
      - run:
          name: Run Tests
          command: |
            npm test
            # Or if you use npm:
            # npm test